version: "3.9"

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet:  192.168.99.0/24
    

services:  
  # nginx
  web-misur:
    image: nginx:1.25.1-alpine
    container_name: web-misur
    restart: unless-stopped
    ports: 
      - "8080:80"
    volumes:
      - ../php/src/misur:/var/www/misur
      - ./nginx/conf.d/default-misur.conf:/etc/nginx/conf.d/default-misur.conf
    links:
      - php-fpm-misur
    networks:
      default:
        aliases:
          - mis_network
  
  web-cmbiz:
    image: nginx:1.25.1-alpine
    container_name: web-cmbiz
    restart: unless-stopped
    ports: 
      - "8081:80"
    volumes:
      - ../php/src/cmbiz:/var/www/cmbiz
      - ./nginx/conf.d/default-cmbiz.conf:/etc/nginx/conf.d/default-cmbiz.conf
    links:
      - php-fpm-cmbiz
    networks:
      default:
        aliases:
          - mis_network
  
  web-rems:
    image: nginx:1.25.1-alpine
    container_name: web-rems
    restart: unless-stopped
    ports: 
      - "8082:80"
    volumes:
      - ../php/src/rems:/var/www/rems
      - ./nginx/conf.d/default-rems.conf:/etc/nginx/conf.d/default-rems.conf
    links:
      - php-fpm-rems
    networks:
      default:
        aliases:
          - mis_network
  
  web-csc:
    image: nginx:1.25.1-alpine
    container_name: web-csc
    restart: unless-stopped
    ports: 
      - "8083:80"
    volumes:
      - ../php/src/csc:/var/www/csc
      - ./nginx/conf.d/default-csc.conf:/etc/nginx/conf.d/default-csc.conf
    links:
      - php-fpm-csc
    networks:
      default:
        aliases:
          - mis_network
  
  php-fpm-misur:
    image: php:8.2.5-fpm-alpine
    container_name: php-fpm-misur
    restart: always
    volumes:
      - ../php/src/misur:/var/www/misur
      #- ../php/config/php.ini:/usr/local/etc/php/php.ini
    networks:
      default:
        aliases:
          - mis_network
  
  php-fpm-cmbiz:
    image: php:8.2.5-fpm-alpine
    container_name: php-fpm-cmbiz
    restart: always
    volumes:
      - ../php/src/cmbiz:/var/www/cmbiz
      #- ../php/config/php.ini:/usr/local/etc/php/php.ini
    networks:
      default:
        aliases:
          - mis_network

  php-fpm-rems:
    image: php:8.2.5-fpm-alpine
    container_name: php-fpm-rems
    restart: always
    volumes:
      - ../php/src/rems:/var/www/rems
      #- ../php/config/php.ini:/usr/local/etc/php/php.ini
    networks:
      default:
        aliases:
          - mis_network
  

  php-fpm-csc:
    image: php:8.2.5-fpm-alpine
    container_name: php-fpm-csc
    restart: always
    volumes:
      - ../php/src/csc:/var/www/csc
      #- ../php/config/php.ini:/usr/local/etc/php/php.ini
    networks:
      default:
        aliases:
          - mis_network




